# -*- coding: utf-8 -*-
"""assignment_1_decision_tree.ipynb !

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vvO62Ai3zUwsGKRDa8qAZHfjVppwgiT8
"""

# Commented out IPython magic to ensure Python compatibility.
from google.colab import drive

drive.mount('/content/drive')
#you arer going to need to place the dataset into the right directory on Google Drive for this to work properly.
#Q1. Modify the following line of code or put the dataset into the right directory.
# %cd /content/drive/My Drive/

import pandas as pd

data = pd.read_csv('vertebrate.csv',header='infer')
data

#Q2.
# (1)please write a few lines of code (as you see fit) to replace all the non-mammals suhc as birds, fishes, amphibians and reptiles
# with 'non-mammal' in the column named 'Class'.
def  nonMammal(word):
  if (word == "mammals"):
    return "mammals"
  else:
    return "non-mammals"



data["Class"] = data["Class"].apply(nonMammal)
#(2) please provide an explanation for why it may be a good idea to congregate different animals into one single category such as 'non-mammals' here?

#Hint: you may search for an answer such as 'how to replace a certain value with a different value in a column in a pandas dataframe'.
#you are going to need to develop the ability to phrase a question like this.

from sklearn import tree

Y = data['Class']
X = data.drop(['Name','Class'],axis=1)



clf = tree.DecisionTreeClassifier(criterion='entropy',max_depth=3)
clf = clf.fit(X, Y)

#Q3
#if you do everything right, you should have no problem running the followng code and getting a tree chart.
#please include the tree chart in your report. It is very important for you to answer the following question.

import pydotplus
from IPython.display import Image

dot_data = tree.export_graphviz(clf, feature_names=X.columns, class_names=['mammals','non-mammals'], filled=True, out_file=None)
graph = pydotplus.graph_from_dot_data(dot_data)
Image(graph.create_png())

# Q4 inteprete the tree chart.
# We spent a good 10 to 15 minuts talking about how to 'read' a tree in the class.
#Here, it is a tree that has only a few levels.
#Explain how the decision tree model seems to do a good job in classifying animal into
#mammals and non-mammals.
# In other words, do you think 'warm-blooded', 'gives-birth' and so forth are useful features for us to classify animals.
#you neeed to explain the decisioin process until you reach all the 'leaves'.
# A leaf is a node that doesn't have child node. Well, you've taken CS 207.

Based on the entropy being .918, very close to 1 means based on the information given,
it is reasonably certain that it will be able to determine if the animal is warm-blooded.
If the entropy, for example, was .20,
 that means the decision tree wouldn't be able to make a decision with a high level of certainty.
